/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firmain;

import static firmain.search.found1;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Ishu
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents(); 
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        search = new javax.swing.JButton();
        viewall = new javax.swing.JButton();
        info = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sorter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(700, 500));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("ATRIA POLICE DEPARTMENT");

        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fir/images/Add.png"))); // NOI18N
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fir/images/Search.png"))); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        viewall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fir/images/Update.png"))); // NOI18N
        viewall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewallActionPerformed(evt);
            }
        });

        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fir/images/look.png"))); // NOI18N
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel2.setText("REGISTER FIR");

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel3.setText("SEARCH FOR FIR");

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel4.setText("REGISTER COMPLAINT");

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel5.setText("POLICEMAN INFO");

        sorter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sorter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fir/images/sort.png"))); // NOI18N
        sorter.setText("SORT");
        sorter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sorterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(register)
                            .addComponent(search))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(viewall)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addGap(59, 59, 59))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(79, 79, 79))))
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(sorter)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewall, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4))
                    .addComponent(register))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel3))
                            .addComponent(search)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel5)))
                .addGap(42, 42, 42)
                .addComponent(sorter)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        // TODO add your handling code here:
        
        policeinfo pf=new policeinfo();
        setVisible(false);
        pf.setVisible(true);
    }//GEN-LAST:event_infoActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        register rm=new register();
        setVisible(false);
        rm.setVisible(true);
    }//GEN-LAST:event_registerActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        search ser=new search();
        setVisible(false);
        ser.setVisible(true);
    }//GEN-LAST:event_searchActionPerformed

    private void viewallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewallActionPerformed
        // TODO add your handling code here:
        register2 regin=new register2();
        setVisible(false);
        regin.setVisible(true);
    }//GEN-LAST:event_viewallActionPerformed

    private void sorterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sorterActionPerformed
        quicksort qt=new quicksort();
        qt.quick();
        
        String firno;
        char buffer2[];
        try{
            
            ArrayList<String> lines = (ArrayList<String>) Files.readAllLines(Paths.get("D:\\1AT15IS034\\6th sem\\sortfinal.txt"));
          
            char buffer[];
            
            FileWriter writer = new FileWriter("D:\\1AT15IS034\\6th sem\\registersort.txt", false);
            BufferedWriter bw = new BufferedWriter(writer);
            for (String line : lines) {
                
                    firno="";
                  
                    buffer=line.toCharArray();
                    int j = 0;
                    
                        while(buffer[j]!=':'){
                            //name+=buffer[j++];
                            j++;
                        }j++;
                        while(buffer[j]!='|')
                           firno+=buffer[j++];
                        j++;
                      
            String fname ="",age ="",phone ="", address ="", aadhar ="";
            String name="";
            ArrayList<String> lines1= (ArrayList<String>) Files.readAllLines(Paths.get("D:\\1AT15IS034\\6th sem\\register.txt"));
            for (String line1 : lines1) {
                
                        if(line1.startsWith(firno)){ 
                            //if the line starts with the given fir no. in register.txt
                            buffer2=line1.toCharArray();
                        int i = 0;
                         while(buffer2[i]!=':'){
                                i++;
                        }i++;
                        
                        while(buffer2[i]!='|')
                           name+=buffer2[i++];
                        i++;
                        while(buffer2[i]!='|')
                            fname+=buffer2[i++];
                        i++;
                        while(buffer2[i]!='|')
                            age+=buffer2[i++];
                        i++;
                        while(buffer2[i]!='|')
                            phone+=buffer2[i++];
                        i++;
                        while(buffer2[i]!='|')
                            address+=buffer2[i++];
                        i++;
                        while(buffer2[i]!='$')
                            aadhar+=buffer2[i++];    
                        
                    }
                    
                }
            //Reading second file for writing
            ArrayList<String> lines2 = (ArrayList<String>) Files.readAllLines(Paths.get("D:\\1AT15IS034\\6th sem\\register2.txt"));
            
            String name1 = "",fname1 ="",age1 ="",phone1 ="", address1 ="", aadhar1 ="";
            char buffer1[];
            
            for (String line2 : lines2) {
                if(line2.startsWith(firno)){
                    //opening second file that is register2.txt for reading its contents according to the sorted firno
                    buffer1=line2.toCharArray();
                    int k = 0;
                    
                        while(buffer1[k]!=':'){
                            k++;
                        }k++;
                        
                        while(buffer1[k]!='|')
                           name1+=buffer1[k++];
                        k++;
                        while(buffer1[k]!='|')
                            fname1+=buffer1[k++];
                        k++;
                        while(buffer1[k]!='|')
                            age1+=buffer1[k++];
                        k++;
                        while(buffer1[k]!='|')
                            phone1+=buffer1[k++];
                        k++;
                        while(buffer1[k]!='|')
                            address1+=buffer1[k++];
                        k++;
                        while(buffer1[k]!='$')
                            aadhar1+=buffer1[k++];
            
            
                    }
                }
                bw.write(name +"-->"+firno+ "|" + fname + "|" + age + "|"+phone+"|"+address+"|"+aadhar+" (Complaint On)-->"
                        +name1 + "|" + fname1 + "|" + age1 + "|"+phone1+"|"+address1+"|"+aadhar1+" $$");
                bw.newLine();
            }    
            bw.close();
            writer.close();

        } catch (IOException ex) {
            // looks like the file not found with given path
           JOptionPane.showMessageDialog(null, ex);   
        }
        
                
            String e="Sorting Done";
        JOptionPane.showMessageDialog(null, e);    
       
    }//GEN-LAST:event_sorterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton register;
    private javax.swing.JButton search;
    private javax.swing.JButton sorter;
    private javax.swing.JButton viewall;
    // End of variables declaration//GEN-END:variables
}
